from __future__ import annotations

from collections.abc import Collection, Mapping, Sequence
from typing import Any

from dnd_dm_assistant.domain.advancement import (
    merge_spell_slot_resources,
    validate_multiclass_prerequisites,
)
from dnd_dm_assistant.domain.advancement_choices import (
    SPELLCASTING_CLASSES,
    canonical_class_name,
    maximum_class_spell_level,
)

ABILITY_KEYS = (
    "strength",
    "dexterity",
    "constitution",
    "intelligence",
    "wisdom",
    "charisma",
)
STANDARD_ARRAY = (8, 10, 12, 13, 14, 15)
POINT_BUY_COSTS = {8: 0, 9: 1, 10: 2, 11: 3, 12: 4, 13: 5, 14: 7, 15: 9}
ABILITY_GENERATION_LABELS = {
    "standard_array": "标准数组",
    "point_buy": "27 点购点",
    "rolled_4d6_drop_lowest": "4d6 去最低",
}
CORE_LANGUAGES = frozenset(
    {
        "通用语",
        "矮人语",
        "精灵语",
        "巨人语",
        "侏儒语",
        "地精语",
        "半身人语",
        "兽人语",
        "龙语",
        "炼狱语",
    }
)


def ability_generation_label(method: str) -> str:
    try:
        return ABILITY_GENERATION_LABELS[method]
    except KeyError as exc:
        raise ValueError(f"未知属性生成方法：{method}") from exc


def validate_ability_generation(
    method: str,
    ability_scores: object,
    *,
    origin_ability_increases: object,
    allowed_origin_abilities: Collection[str],
    ability_rolls: object = None,
) -> dict[str, int]:
    """Validate a level-one score source before 2024 background increases.

    Dice are supplied by the player rather than generated by the server.  This
    makes the roll method auditable while keeping all randomness at the table.
    """

    ability_generation_label(method)
    scores = _ability_mapping(ability_scores, label="属性")
    if set(scores) != set(ABILITY_KEYS):
        raise ValueError("属性必须恰好包含力量、敏捷、体质、智力、感知、魅力")
    origin = _origin_increases(origin_ability_increases, allowed_origin_abilities)
    if any(score < 3 or score > 20 for score in scores.values()):
        raise ValueError("最终属性必须介于 3 到 20 之间")
    base_scores = {key: score - origin.get(key, 0) for key, score in scores.items()}
    if any(score < 3 or score > 18 for score in base_scores.values()):
        raise ValueError("背景起源加值前的属性必须介于 3 到 18 之间")

    if method == "standard_array":
        if sorted(base_scores.values()) != list(STANDARD_ARRAY):
            raise ValueError("标准数组必须为 15/14/13/12/10/8，且每项只能使用一次")
    elif method == "point_buy":
        if any(score not in POINT_BUY_COSTS for score in base_scores.values()):
            raise ValueError("27 点购点的起始属性必须介于 8 到 15 之间")
        if sum(POINT_BUY_COSTS[score] for score in base_scores.values()) != 27:
            raise ValueError("27 点购点必须恰好花费 27 点")
    elif method == "rolled_4d6_drop_lowest":
        rolls = _ability_rolls(ability_rolls)
        mismatches = [
            key
            for key in ABILITY_KEYS
            if sum(sorted(rolls[key])[1:]) != base_scores[key]
        ]
        if mismatches:
            raise ValueError(
                "4d6 去最低的属性与所填骰子不一致：" + "、".join(mismatches)
            )
    else:
        raise ValueError(f"未知属性生成方法：{method}")
    return scores


def validate_languages(
    values: object,
    *,
    available: Collection[str] = CORE_LANGUAGES,
) -> tuple[str, ...]:
    """Return Common plus the two additional languages chosen at creation."""

    if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
        raise ValueError("请选择两门额外语言")
    choices = tuple(str(value).strip() for value in values if str(value).strip())
    if len(choices) != 2 or len(set(choices)) != 2:
        raise ValueError("必须选择两门不重复的额外语言")
    if "通用语" in choices:
        raise ValueError("通用语已自动获得；请选择两门其他语言")
    unknown = sorted(set(choices) - set(available))
    if unknown:
        raise ValueError("所选语言不在 2024 核心语言列表中：" + "、".join(unknown))
    return ("通用语", *choices)


def validate_character_state(
    value: Mapping[str, Any],
    *,
    require_complete_abilities: bool = False,
    enabled_rule_extensions: Collection[str] = (),
    dm_override_reason: str | None = None,
) -> dict[str, Any]:
    """Validate the persisted character invariants shared by all creation paths.

    Player creation performs its catalog-specific selections first, while DM
    imports may intentionally be partial.  This validator therefore owns only
    invariants that must remain true for either path and returns normalized data
    suitable for persistence.
    """

    data = dict(value)
    level = _integer(data.get("level", 1), label="角色等级")
    if not 1 <= level <= 20:
        raise ValueError("角色等级必须介于 1 到 20 之间")
    data["level"] = level

    raw_class_name = str(data.get("class_name") or "").strip()
    class_name = canonical_class_name(raw_class_name) if raw_class_name else ""
    if raw_class_name:
        data["class_name"] = class_name

    raw_class_levels = data.get("class_levels") or {}
    if not isinstance(raw_class_levels, Mapping):
        raise ValueError("职业等级必须是键值表")
    class_levels: dict[str, int] = {}
    for raw_name, raw_level in raw_class_levels.items():
        name = canonical_class_name(str(raw_name).strip())
        if not name:
            raise ValueError("职业等级中的职业名不能为空")
        class_level = _integer(raw_level, label=f"{name}职业等级")
        if not 1 <= class_level <= 20:
            raise ValueError(f"{name}职业等级必须介于 1 到 20 之间")
        if name in class_levels:
            raise ValueError(f"职业等级包含重复职业：{name}")
        class_levels[name] = class_level
    if class_name and not class_levels:
        class_levels[class_name] = level
    if class_levels:
        if sum(class_levels.values()) != level:
            raise ValueError("各职业等级之和必须等于角色总等级")
        if class_name and class_name not in class_levels:
            raise ValueError("主职业必须出现在职业等级中")
    data["class_levels"] = class_levels

    raw_subclasses = data.get("subclass_choices") or {}
    if not isinstance(raw_subclasses, Mapping):
        raise ValueError("子职选择必须是键值表")
    subclasses: dict[str, str] = {}
    for raw_name, raw_subclass in raw_subclasses.items():
        name = canonical_class_name(str(raw_name).strip())
        subclass = str(raw_subclass).strip()
        if not name or not subclass:
            raise ValueError("子职选择中的职业与子职名称不能为空")
        if name not in class_levels:
            raise ValueError(f"不能为未拥有的职业选择子职：{name}")
        if class_levels[name] < 3:
            raise ValueError(f"{name}达到 3 级后才能记录子职")
        subclasses[name] = subclass
    data["subclass_choices"] = subclasses

    raw_scores = data.get("ability_scores") or {}
    scores = _ability_mapping(raw_scores, label="属性")
    unknown_abilities = sorted(set(scores) - set(ABILITY_KEYS))
    if unknown_abilities:
        raise ValueError("存在未知属性：" + "、".join(unknown_abilities))
    if require_complete_abilities and set(scores) != set(ABILITY_KEYS):
        raise ValueError("属性必须恰好包含力量、敏捷、体质、智力、感知、魅力")
    if any(score < 3 or score > 30 for score in scores.values()):
        raise ValueError("属性必须介于 3 到 30 之间")
    data["ability_scores"] = scores

    # Direct DM editing and player creation both reach this contract.  The
    # catalog-specific player flow has one class at level one, while DM imports
    # may be multi-class; make the latter obey the same campaign gate used by
    # the advancement workflow unless the DM deliberately records an override.
    override = str(dm_override_reason or "").strip()
    if len(class_levels) > 1:
        enabled = {str(item).strip() for item in enabled_rule_extensions}
        if "multiclassing" not in enabled and not override:
            raise ValueError("本战役未启用兼职规则，不能保存多职业角色")
        failures = [
            f"{name}：{', '.join(validate_multiclass_prerequisites(name, scores))}"
            for name in sorted(class_levels)
            if validate_multiclass_prerequisites(name, scores)
        ]
        if failures and not override:
            raise ValueError("多职业属性前置条件不满足：" + "；".join(failures))

    hp = _integer(data.get("hp", 0), label="当前生命值")
    max_hp = _integer(data.get("max_hp", 0), label="最大生命值")
    if hp < 0 or max_hp < 0 or hp > max_hp:
        raise ValueError("当前生命值必须介于 0 和最大生命值之间")
    data["hp"] = hp
    data["max_hp"] = max_hp

    raw_resources = data.get("resources") or {}
    if not isinstance(raw_resources, Mapping):
        raise ValueError("资源必须是键值表")
    resources: dict[str, Any] = {}
    for raw_key, raw_resource in raw_resources.items():
        key = str(raw_key).strip()
        if not key:
            raise ValueError("资源键不能为空")
        if not isinstance(raw_resource, Mapping):
            raise ValueError(f"资源{key}必须是记录")
        resource = dict(raw_resource)
        maximum = _integer(
            resource.get("max", resource.get("maximum", 0)),
            label=f"资源{key}上限",
        )
        current = _integer(
            resource.get("current", maximum), label=f"资源{key}当前值"
        )
        if maximum < 0 or current < 0 or current > maximum:
            raise ValueError(f"资源{key}当前值必须介于 0 和上限之间")
        recovery = resource.get("recovery")
        if recovery is not None and not isinstance(recovery, str):
            raise ValueError(f"资源{key}恢复时机必须是文本")
        resource["max"] = maximum
        resource["current"] = current
        resource.pop("maximum", None)
        resources[key] = resource
    data["resources"] = resources
    # Character creation and direct DM edits share the same multiclass slot
    # contract as advancement.  Preserve spent slots while recalculating the
    # shared table; Pact Magic remains a distinct resource in the helper.
    if class_levels and any(name in SPELLCASTING_CLASSES for name in class_levels):
        data["resources"] = merge_spell_slot_resources(
            resources,
            class_levels,
            subclasses,
        )

    data["features"] = _normalize_sheet_entries(
        data.get("features") or [],
        label="特性",
        canonicalize_class=True,
    )
    data["actions"] = _normalize_sheet_entries(
        data.get("actions") or [],
        label="动作",
        canonicalize_class=True,
    )

    raw_spells = data.get("spells") or []
    if not isinstance(raw_spells, Sequence) or isinstance(raw_spells, (str, bytes)):
        raise ValueError("法术表必须是列表")
    seen_spells: set[str] = set()
    spells: list[Any] = []
    for raw_spell in raw_spells:
        if not isinstance(raw_spell, Mapping):
            raise ValueError("法术表中的每项都必须是法术记录")
        spell = dict(raw_spell)
        name = str(spell.get("name") or "").strip()
        source_id = str(spell.get("source_record_id") or "").strip()
        identity = source_id or name
        if not identity:
            raise ValueError("法术名称或来源记录不能为空")
        if identity in seen_spells:
            raise ValueError(f"法术表包含重复法术：{name or source_id}")
        seen_spells.add(identity)
        spell_level = _integer(
            spell.get("spell_level", spell.get("level", 0)),
            label=f"法术{name or source_id}环级",
        )
        if not 0 <= spell_level <= 9:
            raise ValueError(f"法术{name or source_id}环级必须介于 0 到 9 之间")
        if spell_level == 0 and spell.get("prepared") is False:
            raise ValueError("戏法必须标记为始终可用")
        spell_class = canonical_class_name(str(spell.get("class_name") or "").strip())
        if spell_class:
            if class_levels and spell_class not in class_levels:
                raise ValueError(f"法术{name or source_id}关联了未拥有的职业{spell_class}")
            if spell_class in SPELLCASTING_CLASSES:
                maximum_level = maximum_class_spell_level(
                    spell_class, class_levels.get(spell_class, 0)
                )
                if spell_level > maximum_level:
                    raise ValueError(
                        f"法术{name or source_id}环级超过{spell_class}职业等级允许范围"
                    )
            spell["class_name"] = spell_class
        spell["spell_level"] = spell_level
        spells.append(spell)
    data["spells"] = spells
    return data


def _normalize_sheet_entries(
    values: object,
    *,
    label: str,
    canonicalize_class: bool,
) -> list[Any]:
    """Normalize the shared free-form feature/action sheet shape.

    Legacy sheets may use display strings, so those remain valid.  Structured
    entries get a small, stable runtime contract shared by DM edits and player
    creation: named entries may state only ``full``, ``partial`` or ``dm_only``
    automation and must keep an explicit DM-adjudication flag when supplied.
    """

    if not isinstance(values, Sequence) or isinstance(values, (str, bytes)):
        raise ValueError(f"{label}必须是列表")
    normalized: list[Any] = []
    for entry in values:
        if isinstance(entry, str):
            text = entry.strip()
            if not text:
                raise ValueError(f"{label}名称不能为空")
            normalized.append(text)
            continue
        if not isinstance(entry, Mapping):
            raise ValueError(f"{label}中的每项必须是文本或记录")
        item = dict(entry)
        name = str(item.get("name") or "").strip()
        if not name:
            raise ValueError(f"{label}记录必须包含名称")
        item["name"] = name
        if canonicalize_class and item.get("class_name"):
            item["class_name"] = canonical_class_name(str(item["class_name"]).strip())
        runtime = item.get("runtime")
        if runtime is not None:
            if not isinstance(runtime, Mapping):
                raise ValueError(f"{label}{name}的运行时状态必须是记录")
            normalized_runtime = dict(runtime)
            status = str(normalized_runtime.get("automation_status") or "dm_only")
            if status not in {"full", "partial", "dm_only"}:
                raise ValueError(f"{label}{name}的自动化状态无效")
            normalized_runtime["automation_status"] = status
            if "requires_dm_adjudication" in normalized_runtime:
                normalized_runtime["requires_dm_adjudication"] = bool(
                    normalized_runtime["requires_dm_adjudication"]
                )
            item["runtime"] = normalized_runtime
        normalized.append(item)
    return normalized


def _ability_mapping(value: object, *, label: str) -> dict[str, int]:
    if not isinstance(value, Mapping):
        raise ValueError(f"{label}必须是键值表")
    result: dict[str, int] = {}
    for raw_key, raw_value in value.items():
        key = str(raw_key).strip()
        if not key:
            raise ValueError(f"{label}名称不能为空")
        if isinstance(raw_value, bool):
            raise ValueError(f"{label}{key}必须是整数")
        try:
            result[key] = int(raw_value)
        except (TypeError, ValueError) as exc:
            raise ValueError(f"{label}{key}必须是整数") from exc
    return result


def _integer(value: object, *, label: str) -> int:
    if isinstance(value, bool):
        raise ValueError(f"{label}必须是整数")
    try:
        return int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{label}必须是整数") from exc


def _origin_increases(values: object, allowed: Collection[str]) -> dict[str, int]:
    increases = _ability_mapping(values, label="背景起源属性加值")
    allowed_set = {str(value) for value in allowed}
    invalid = sorted(set(increases) - allowed_set)
    if invalid:
        raise ValueError("背景起源不能提升这些属性：" + "、".join(invalid))
    if any(value not in {1, 2} for value in increases.values()):
        raise ValueError("背景起源属性加值只能是 +1 或 +2")
    pattern = sorted(increases.values())
    if pattern not in ([1, 2], [1, 1, 1]):
        raise ValueError("背景起源必须选择 +2/+1 两项不同属性，或三项各 +1")
    return increases


def _ability_rolls(values: object) -> dict[str, tuple[int, int, int, int]]:
    if not isinstance(values, Mapping):
        raise ValueError("4d6 去最低必须提交每项属性的四个骰子")
    result: dict[str, tuple[int, int, int, int]] = {}
    if {str(key).strip() for key in values} != set(ABILITY_KEYS):
        raise ValueError("4d6 去最低必须为六项属性分别提交骰子")
    for raw_key, raw_rolls in values.items():
        key = str(raw_key).strip()
        if not isinstance(raw_rolls, Sequence) or isinstance(raw_rolls, (str, bytes)):
            raise ValueError(f"{key}必须提交四个 d6 结果")
        if len(raw_rolls) != 4:
            raise ValueError(f"{key}必须提交四个 d6 结果")
        rolls: list[int] = []
        for raw_roll in raw_rolls:
            if isinstance(raw_roll, bool):
                raise ValueError(f"{key}的骰子必须是 1 到 6")
            try:
                roll = int(raw_roll)
            except (TypeError, ValueError) as exc:
                raise ValueError(f"{key}的骰子必须是 1 到 6") from exc
            if not 1 <= roll <= 6:
                raise ValueError(f"{key}的骰子必须是 1 到 6")
            rolls.append(roll)
        result[key] = (rolls[0], rolls[1], rolls[2], rolls[3])
    return result
