// ---------------------------------------------------------------------------
// 5e Test & Standard Spells Catalog for Player Selection & Upcasting
// ---------------------------------------------------------------------------
export type CombatSpellOption = {
  id: string;
  name: string;
  nameEn: string;
  level: number; // 0 for cantrips, 1..9
  school: string;
  castTime: string; // "1动作", "附赠动作", "反应"
  rangeFt: number; // e.g. 120, 60, 150, 5, 0 (Self)
  shape: "single" | "sphere" | "cone" | "line" | "cube";
  sizeFt?: number; // e.g. 20 (for 20ft sphere/cube/cone)
  originSelf?: boolean;
  damageDiceBase: string; // e.g. "1d10", "3d6", "8d6", "2d8", "1d4+1"
  damageType: string; // "fire", "force", "thunder", "radiant", "lightning", "cold", "healing"
  isAttackRoll: boolean; // true for attack roll, false for saving throw / auto-hit
  saveAbility?: string; // "DEX", "CON", "WIS"
  upcastRule: string; // e.g. "+1d6 伤害/环", "+1 枚飞弹/环", "+1d8 伤害/环"
  description: string;
  vfx: "fire" | "arcane" | "shockwave" | "smite" | "slash";
};

export const DND_TEST_SPELLS: CombatSpellOption[] = [
  {
    id: "fire_bolt",
    name: "火焰箭",
    nameEn: "Fire Bolt",
    level: 0,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 120,
    shape: "single",
    damageDiceBase: "1d10",
    damageType: "fire",
    isAttackRoll: true,
    upcastRule: "人物等级提升时伤害成长 (5级2d10 / 11级3d10)",
    description: "向射程内单一目标投掷炽热火束，造成 1d10 火焰伤害并可点燃未被携带的可燃物。",
    vfx: "fire",
  },
  {
    id: "sacred_flame",
    name: "圣火术",
    nameEn: "Sacred Flame",
    level: 0,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 60,
    shape: "single",
    damageDiceBase: "1d8",
    damageType: "radiant",
    isAttackRoll: false,
    saveAbility: "DEX",
    upcastRule: "人物等级提升时伤害成长 (5级2d8 / 11级3d8)",
    description: "类似光耀烈焰自天而降照射目标，目标须通过敏捷豁免，否则受到 1d8 光耀伤害。目标无法从掩蔽中获得豁免增益。",
    vfx: "smite",
  },
  {
    id: "chill_touch",
    name: "冻寒之触",
    nameEn: "Chill Touch",
    level: 0,
    school: "死灵",
    castTime: "1动作",
    rangeFt: 120,
    shape: "single",
    damageDiceBase: "1d8",
    damageType: "necrotic",
    isAttackRoll: true,
    upcastRule: "人物等级提升时伤害成长 (5级2d8)",
    description: "在目标空间创造一只骷髅幽灵鬼手，造成 1d8 黯蚀伤害，并在你下回合开始前阻止其恢复生命值。",
    vfx: "arcane",
  },
  {
    id: "magic_missile",
    name: "魔法飞弹",
    nameEn: "Magic Missile",
    level: 1,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 120,
    shape: "single",
    damageDiceBase: "1d4+1",
    damageType: "force",
    isAttackRoll: false,
    upcastRule: "使用2环或更高法术位时，每高1环便多创造 1 枚飞弹",
    description: "创造 3 枚必中发光的秘法力场飞弹，每枚造成 1d4+1 力场伤害，可分别射向同一或不同敌人。",
    vfx: "arcane",
  },
  {
    id: "thunderwave",
    name: "雷鸣波",
    nameEn: "Thunderwave",
    level: 1,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 15,
    shape: "cube",
    sizeFt: 15,
    originSelf: true,
    damageDiceBase: "2d8",
    damageType: "thunder",
    isAttackRoll: false,
    saveAbility: "CON",
    upcastRule: "使用2环或更高法术位时，每高1环伤害增加 1d8",
    description: "自自身迸发雷鸣震波，立方体内所有生物须通过体质豁免，失败承受 2d8 雷鸣伤害并被推开 10 尺（2格）。",
    vfx: "shockwave",
  },
  {
    id: "burning_hands",
    name: "燃烧之手",
    nameEn: "Burning Hands",
    level: 1,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 15,
    shape: "cone",
    sizeFt: 15,
    originSelf: true,
    damageDiceBase: "3d6",
    damageType: "fire",
    isAttackRoll: false,
    saveAbility: "DEX",
    upcastRule: "使用2环或更高法术位时，每高1环伤害增加 1d6",
    description: "双手张开喷涌出一道 15 尺扇形锥状烈焰，区域内生物敏捷豁免失败承受 3d6 火焰伤害（成功半伤）。",
    vfx: "fire",
  },
  {
    id: "healing_word",
    name: "治愈真言",
    nameEn: "Healing Word",
    level: 1,
    school: "塑能",
    castTime: "附赠动作",
    rangeFt: 60,
    shape: "single",
    damageDiceBase: "1d4+3",
    damageType: "healing",
    isAttackRoll: false,
    upcastRule: "使用2环或更高法术位时，每高1环治疗量增加 1d4",
    description: "以轻柔祷言治愈射程内的一名可见生物，回复 1d4 + 关键施法属性调整值的生命值。",
    vfx: "smite",
  },
  {
    id: "scorching_ray",
    name: "灼热射线",
    nameEn: "Scorching Ray",
    level: 2,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 120,
    shape: "single",
    damageDiceBase: "2d6",
    damageType: "fire",
    isAttackRoll: true,
    upcastRule: "使用3环或更高法术位时，每高1环便多创造 1 条炽热射线",
    description: "射出 3 道炽热的光束，为每道光束独立进行远程法术攻击，命中造成 2d6 火焰伤害。",
    vfx: "fire",
  },
  {
    id: "shatter",
    name: "碎击波",
    nameEn: "Shatter",
    level: 2,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 60,
    shape: "sphere",
    sizeFt: 10,
    damageDiceBase: "3d8",
    damageType: "thunder",
    isAttackRoll: false,
    saveAbility: "CON",
    upcastRule: "使用3环或更高法术位时，每高1环伤害增加 1d8",
    description: "在射程内指定点爆发出刺耳高频音波（10尺半径球体），造成 3d8 雷鸣伤害，对无机物材质格外致命。",
    vfx: "shockwave",
  },
  {
    id: "misty_step",
    name: "迷踪步",
    nameEn: "Misty Step",
    level: 2,
    school: "咒法",
    castTime: "附赠动作",
    rangeFt: 30,
    shape: "single",
    damageDiceBase: "0",
    damageType: "utility",
    isAttackRoll: false,
    upcastRule: "固定2环",
    description: "被银色迷雾包裹并瞬间传送到 30 尺内可见的一处未被占据的空间（可跨越障碍与脱离纠缠）。",
    vfx: "arcane",
  },
  {
    id: "fireball",
    name: "火球术",
    nameEn: "Fireball",
    level: 3,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 150,
    shape: "sphere",
    sizeFt: 20,
    damageDiceBase: "8d6",
    damageType: "fire",
    isAttackRoll: false,
    saveAbility: "DEX",
    upcastRule: "使用4环或更高法术位时，每高1环伤害增加 1d6",
    description: "自指尖射出一枚明亮火星，在目标点（20尺半径球体）猛烈炸开，范围内生物敏捷豁免失败承受 8d6 火焰伤害（成功半伤）。",
    vfx: "fire",
  },
  {
    id: "lightning_bolt",
    name: "闪电束",
    nameEn: "Lightning Bolt",
    level: 3,
    school: "塑能",
    castTime: "1动作",
    rangeFt: 100,
    shape: "line",
    sizeFt: 100,
    originSelf: true,
    damageDiceBase: "8d6",
    damageType: "lightning",
    isAttackRoll: false,
    saveAbility: "DEX",
    upcastRule: "使用4环或更高法术位时，每高1环伤害增加 1d6",
    description: "自自身释放出一条长 100 尺、宽 5 尺的爆裂雷电巨蟒，直线上所有生物敏捷豁免失败承受 8d6 闪电伤害。",
    vfx: "smite",
  },
  {
    id: "hypnotic_pattern",
    name: "催眠图纹",
    nameEn: "Hypnotic Pattern",
    level: 3,
    school: "幻术",
    castTime: "1动作",
    rangeFt: 120,
    shape: "cube",
    sizeFt: 30,
    damageDiceBase: "0",
    damageType: "condition",
    isAttackRoll: false,
    saveAbility: "WIS",
    upcastRule: "固定3环",
    description: "在空中编织出炫丽迷幻的光彩图案（30尺立方体），区域内生物感知豁免失败陷入【魅惑】与【失能】（速度归零）。",
    vfx: "arcane",
  },
];

// ---------------------------------------------------------------------------
// 5e Conditions Metadata & Rules
// ---------------------------------------------------------------------------
export const DND_CONDITIONS = [
  { id: "prone", name: "倒地 (Prone)", icon: "🧎", desc: "攻击者近战具优势，远程具劣势；自身攻击劣势；起身消耗一半移动速度", tone: "warn" as const },
  { id: "poisoned", name: "中毒 (Poisoned)", icon: "🧪", desc: "攻击检定和所有能力检定具有劣势", tone: "danger" as const },
  { id: "frightened", name: "恐慌 (Frightened)", icon: "😨", desc: "不能主动靠近恐惧源；攻击检定和能力检定具有劣势", tone: "danger" as const },
  { id: "restrained", name: "束缚 (Restrained)", icon: "🕸️", desc: "速度为0；自身攻击劣势；针对目标的攻击具有优势；敏捷豁免劣势", tone: "danger" as const },
  { id: "grappled", name: "擒抱 (Grappled)", icon: "🤼", desc: "速度为0；擒抱者移动时可拖动目标", tone: "warn" as const },
  { id: "blinded", name: "目盲 (Blinded)", icon: "👁️‍🗨️", desc: "目标无法看见；针对目标的攻击具优势；目标攻击具劣势；依赖视觉的检定自动失败", tone: "danger" as const },
  { id: "deafened", name: "耳聋 (Deafened)", icon: "🔇", desc: "目标无法听见；依赖听觉的能力检定自动失败", tone: "neutral" as const },
  { id: "charmed", name: "魅惑 (Charmed)", icon: "💖", desc: "不能攻击魅惑者；魅惑者在与该目标的社交检定中具有优势", tone: "neutral" as const },
  { id: "paralyzed", name: "麻痹 (Paralyzed)", icon: "⚡", desc: "失能且无法移动/言语；力量敏捷豁免自动失败；针对目标的攻击具优势；5尺内近战命中直接自动暴击！", tone: "danger" as const },
  { id: "stunned", name: "震慑 (Stunned)", icon: "💫", desc: "失能且无法移动；言语含糊；力量敏捷豁免自动失败；针对目标的攻击具优势", tone: "danger" as const },
  { id: "unconscious", name: "昏迷 (Unconscious)", icon: "💤", desc: "失能、倒地并掉落所持物；力量敏捷豁免自动失败；针对目标的攻击具优势；5尺内近战命中直接自动暴击！", tone: "danger" as const },
  { id: "invisible", name: "隐形 (Invisible)", icon: "👻", desc: "无法被视觉侦测；自身攻击具有优势；针对自身的攻击具有劣势", tone: "ok" as const },
  { id: "incapacitated", name: "失能 (Incapacitated)", icon: "🛑", desc: "不能进行任何动作、附赠动作或反应；无法维持专注", tone: "danger" as const },
  { id: "concentrating", name: "专注 (Concentrating)", icon: "🔮", desc: "正在维持持续性法术；受到伤害需进行体质豁免 (DC 10 或伤害值的一半)", tone: "ai" as const },
  { id: "exhaustion", name: "力竭 (Exhaustion)", icon: "⌛", desc: "等级累加减值（检定劣势、速度减半、攻击豁免劣势等）", tone: "danger" as const },
];

// ---------------------------------------------------------------------------
// 5e 18 Skills Definitions
// ---------------------------------------------------------------------------
export const DND_SKILLS = [
  { id: "athletics", name: "运动 (Athletics)", ability: "STR", desc: "攀爬、跳跃、游泳、擒抱与推撞对决" },
  { id: "acrobatics", name: "体操 (Acrobatics)", ability: "DEX", desc: "走钢丝、特技翻滚、脱离擒抱" },
  { id: "sleight_of_hand", name: "巧手 (Sleight of Hand)", ability: "DEX", desc: "顺手牵羊、隐藏物品、近战缴械" },
  { id: "stealth", name: "隐匿 (Stealth)", ability: "DEX", desc: "潜行、暗中移动、战术躲藏" },
  { id: "arcana", name: "奥秘 (Arcana)", ability: "INT", desc: "回忆魔法知识、法术流派、位面存在" },
  { id: "history", name: "历史 (History)", ability: "INT", desc: "历史事件、古老帝国、贵族家族" },
  { id: "investigation", name: "调查 (Investigation)", ability: "INT", desc: "搜寻隐秘线索、洞察机关破绽" },
  { id: "nature", name: "自然 (Nature)", ability: "INT", desc: "动植物知识、地形、天气与自然规律" },
  { id: "religion", name: "宗教 (Religion)", ability: "INT", desc: "神祇、教派仪式、神圣符号" },
  { id: "animal_handling", name: "驯兽 (Animal Handling)", ability: "WIS", desc: "安抚坐骑、理解动物意图" },
  { id: "insight", name: "洞悉 (Insight)", ability: "WIS", desc: "识破谎言、洞察战术假动作与意图" },
  { id: "medicine", name: "医疗 (Medicine)", ability: "WIS", desc: "战地急救、稳定濒死伤势 (DC 10)" },
  { id: "perception", name: "察觉 (Perception)", ability: "WIS", desc: "侦测周围细节、识破潜伏伏击" },
  { id: "survival", name: "生存 (Survival)", ability: "WIS", desc: "追踪足迹、野外辨位、预知危险" },
  { id: "deception", name: "欺瞒 (Deception)", ability: "CHA", desc: "声东击西、误导敌人、战术佯攻" },
  { id: "intimidation", name: "威吓 (Intimidation)", ability: "CHA", desc: "战吼威压、以气势逼退敌人" },
  { id: "performance", name: "表演 (Performance)", ability: "CHA", desc: "引人注目、分散注意力" },
  { id: "persuasion", name: "说服 (Persuasion)", ability: "CHA", desc: "战地谈判、劝降与调停" },
];
