import type { PrepDraft } from "../api/prep";

export type AdventurePreset = {
  id: string;
  title: string;
  subtitle: string;
  tag: string;
  description: string;
  recommendedLevel: string;
  duration: string;
  features: string[];
  draft: PrepDraft;
};

export const STARTER_ADVENTURE_PRESET: AdventurePreset = {
  id: "duskbell-redfall-refuge",
  title: "黄昏钟声：红落避难所",
  subtitle: "经典 1~3 级新手开团模组 · 沉浸式地牢与悬疑探索",
  tag: "官方推荐新手模组",
  description:
    "在被浓雾笼罩的黄昏钟声小镇，古老避难所的丧钟每逢午夜自鸣。商队神秘失踪，镇长神情慌张，而避难所下层的古老机械正在苏醒。冒险者们受雇深入避难所探查失踪真相与钟声诅咒。",
  recommendedLevel: "1 - 3 级 (适合 3~5 名玩家)",
  duration: "单次短团 (约 3~4 小时)",
  features: [
    "🗺️ 5 个完整层级地下城与战术网格地图",
    "👤 8 位各怀秘密与人际关系的生动 NPC",
    "⚔️ 4 组阶梯难度平衡遭遇 (地精巡逻队、自律守卫、幽魂敲钟人)",
    "📜 3 条主支线任务与多层线索解谜网",
    "💎 专属装备与魔法战利品掉落",
  ],
  draft: {
    schema_version: "1.0",
    title: "黄昏钟声：红落避难所",
    locations: [
      {
        key: "loc_duskbell_town",
        name: "黄昏钟声镇 (Duskbell Town)",
        depth: 1,
        description: "依山而建的古老村镇，常年被灰白色的迷雾环绕。镇中央矗立着高耸的黑曜石钟楼。",
        discovered: true,
        notes: "玩家的初始集结地与补给点，有酒馆和铁匠铺。",
      },
      {
        key: "loc_redfall_keep_entrance",
        parent_location_key: "loc_duskbell_town",
        name: "红落避难所·前厅大殿",
        depth: 2,
        description: "荒废百年的石砌大殿，地面散落着锈蚀的武器与碎裂的烛台，冷风从石缝中呜咽穿过。",
        discovered: true,
        notes: "避难所第一层，常有地精斥候在此扎营。",
      },
      {
        key: "loc_crypt_of_bellringer",
        parent_location_key: "loc_redfall_keep_entrance",
        name: "敲钟人地宫 (Crypt of the Bellringer)",
        depth: 3,
        description: "阴冷潮湿的下层墓室，排列着历代守钟人的石棺。石壁上刻着警告侵入者的古老符文。",
        discovered: false,
        secrets: "中央石棺底部藏有开启炼金工坊的黄铜齿轮钥匙。",
      },
      {
        key: "loc_smugglers_cove",
        parent_location_key: "loc_redfall_keep_entrance",
        name: "地下走私水窟 (Smuggler's Cove)",
        depth: 3,
        description: "避难所地底暗河交汇处，停靠着半沉没的木筏，空气中弥漫着潮湿的腐木与火药味。",
        discovered: false,
      },
      {
        key: "loc_alchemists_tower",
        parent_location_key: "loc_crypt_of_bellringer",
        name: "发条与炼金密室 (Clockwork Lab)",
        depth: 4,
        description: "充满黄铜管道与转动齿轮的高耸密室，巨大的发条核心正散发着幽蓝色的奥术光芒。",
        discovered: false,
        secrets: "破坏核心的三个减速阀可以安全停止自律守卫的充能。",
      },
    ],
    scenes: [
      {
        key: "scene_keep_ambush",
        location_key: "loc_redfall_keep_entrance",
        name: "前厅突袭：地精掠夺队",
        description: "当冒险者踏入大殿时，四名隐藏在碎石柱后面的地精突然发出尖叫，掷出标枪！",
        status: "active",
        grid: {
          width: 14,
          height: 10,
          cell_size_ft: 5,
          mode: "combat",
          public_description: "前厅大殿 (14x10 格，中央有断裂的石柱提供半掩体)",
        },
        participants: [
          { entity_type: "monster", entity_key: "mon_goblin_scout_1", role: "hostile", visible: true },
          { entity_type: "monster", entity_key: "mon_goblin_scout_2", role: "hostile", visible: true },
          { entity_type: "monster", entity_key: "mon_goblin_leader", role: "hostile", visible: true },
        ],
      },
      {
        key: "scene_crypt_guardian",
        location_key: "loc_crypt_of_bellringer",
        name: "地宫幽影：哀鸣守钟人",
        description: "墓室中央的空气骤然降至冰点，一个半透明的身影浮现在石棺上方，手中的虚体丧钟轰然敲响！",
        status: "draft",
        grid: {
          width: 12,
          height: 12,
          cell_size_ft: 5,
          mode: "combat",
          public_description: "敲钟人地宫 (12x12 格，四周石棺阻挡视线)",
        },
        participants: [
          { entity_type: "monster", entity_key: "mon_bellringer_specter", role: "boss", visible: true },
        ],
      },
    ],
    npcs: [
      {
        key: "npc_mayor_eldridge",
        name: "镇长 埃尔德里奇 (Mayor Eldridge)",
        armor_class: 10,
        hp: 12,
        max_hp: 12,
        speed: 30,
        ability_scores: { strength: 10, dexterity: 10, constitution: 11, intelligence: 14, wisdom: 12, charisma: 14 },
        description: "一位身着褪色天鹅绒外套的中年绅士，眼眶深陷，手指总是不安地摩挲着怀表。",
        personality: "谨小慎微，对任何外乡人都带着戒备，但为了小镇安危愿意付出重金。",
        goal: "查明钟声原因并平息恐慌，保住镇长职位。",
        secrets: "他的祖先曾是避难所最后一任督造官，私吞了一批用于封印下层的贵重奥术水晶。",
        attitude: "friendly",
        location_key: "loc_duskbell_town",
      },
      {
        key: "npc_innkeeper_martha",
        name: "酒馆老板娘 玛莎 (Martha Stout)",
        armor_class: 11,
        hp: 18,
        max_hp: 18,
        speed: 30,
        ability_scores: { strength: 14, dexterity: 12, constitution: 14, intelligence: 10, wisdom: 13, charisma: 13 },
        description: "身材微胖、爽朗干练的半身人妇人，围裙口袋里总是装着肉桂糖和厚厚的账本。",
        personality: "热心肠，耳目灵通，只要两杯麦酒就能讲出小镇过去三十年的奇闻八卦。",
        known_information: "两周前看到有戴黑兜帽的商队深夜运送大箱沉重的金属零件前往避难所后山。",
        attitude: "friendly",
        location_key: "loc_duskbell_town",
      },
    ],
    monsters: [
      {
        key: "mon_goblin_scout_1",
        name: "地精斥候·刺尾 (Goblin Scout)",
        armor_class: 15,
        hp: 7,
        max_hp: 7,
        speed: 30,
        challenge_rating: "1/4",
        ability_scores: { strength: 8, dexterity: 14, constitution: 10, intelligence: 10, wisdom: 8, charisma: 8 },
        actions: [
          { name: "弯刀 (Scimitar)", attack_bonus: 4, damage: "1d6+2", damage_type: "slashing", reach_ft: 5 },
          { name: "短弓 (Shortbow)", attack_bonus: 4, damage: "1d6+2", damage_type: "piercing", range_ft: 80 },
        ],
      },
      {
        key: "mon_goblin_scout_2",
        name: "地精斥候·裂牙 (Goblin Scout)",
        armor_class: 15,
        hp: 7,
        max_hp: 7,
        speed: 30,
        challenge_rating: "1/4",
        ability_scores: { strength: 8, dexterity: 14, constitution: 10, intelligence: 10, wisdom: 8, charisma: 8 },
        actions: [
          { name: "弯刀 (Scimitar)", attack_bonus: 4, damage: "1d6+2", damage_type: "slashing", reach_ft: 5 },
          { name: "短弓 (Shortbow)", attack_bonus: 4, damage: "1d6+2", damage_type: "piercing", range_ft: 80 },
        ],
      },
      {
        key: "mon_goblin_leader",
        name: "地精头目 库鲁格 (Kurug the Bold)",
        armor_class: 16,
        hp: 21,
        max_hp: 21,
        speed: 30,
        challenge_rating: "1",
        ability_scores: { strength: 12, dexterity: 15, constitution: 12, intelligence: 10, wisdom: 11, charisma: 10 },
        actions: [
          { name: "多重攻击 (Multiattack)", description: "库鲁格进行两次弯刀攻击。" },
          { name: "精锻弯刀 (Scimitar)", attack_bonus: 5, damage: "1d6+3", damage_type: "slashing", reach_ft: 5 },
        ],
      },
      {
        key: "mon_bellringer_specter",
        name: "哀鸣敲钟人幽影 (Specter of the Bellringer)",
        armor_class: 12,
        hp: 22,
        max_hp: 22,
        speed: 30,
        challenge_rating: "1",
        ability_scores: { strength: 1, dexterity: 14, constitution: 11, intelligence: 10, wisdom: 10, charisma: 11 },
        actions: [
          { name: "汲魂之触 (Life Drain)", attack_bonus: 4, damage: "3d6", damage_type: "necrotic", reach_ft: 5, description: "目标必须通过 DC 10 体质豁免，否则其生命值上限扣减等量伤害。" },
          { name: "幽冥钟声 (Phantom Toll)", damage: "1d12", damage_type: "necrotic", save_ability: "wisdom", save_dc: 12, range_ft: 60 },
        ],
      },
    ],
    quests: [
      {
        key: "quest_silence_the_bells",
        name: "平息午夜钟声 (Silence the Bells)",
        quest_type: "main",
        giver: "镇长 埃尔德里奇",
        giver_npc_key: "npc_mayor_eldridge",
        reward: "150 金币 (GP) 以及避难所搜获的全部合规魔法物品",
        xp_reward: 300,
        status: "open",
        description: "深入红落避难所下层，摧毁或停用引发午夜诡异钟声的失控奥术核心。",
      },
      {
        key: "quest_missing_caravan",
        name: "寻找失踪商队 (The Missing Merchant)",
        quest_type: "side",
        giver: "酒馆老板娘 玛莎",
        giver_npc_key: "npc_innkeeper_martha",
        reward: "一箱精酿矮人麦酒 + 50 银币",
        xp_reward: 150,
        status: "open",
        description: "在避难所外围或地下水窟寻找失踪半身人商人托宾的下落或货物账本。",
      },
    ],
    clues: [
      {
        key: "clue_brass_gear",
        quest_key: "quest_silence_the_bells",
        name: "刻有符文的黄铜齿轮",
        description: "带有精细齿轮咬合纹路的钥匙，似乎能插入某个下层机械控制台。",
        player_text: "一枚沉甸甸的古老黄铜齿轮，上面刻着三道放射状的凹槽。",
        dm_truth: "用于开启发条密室安全减速阀的专用控制密钥。",
        discovered: false,
      },
      {
        key: "clue_smuggler_ledger",
        quest_key: "quest_missing_caravan",
        name: "浸水的羊皮账本",
        description: "记录了避难所走私暗河路线的账本，上面有托宾商会的蜡封标记。",
        player_text: "一本被水浸透但字迹尚存的皮面小册子，记录着货物清单与暗号。",
        dm_truth: "证实地精与黑市走私者勾结，并标记了水窟暗门的开启机关位置。",
        discovered: false,
      },
    ],
    items: [
      {
        key: "item_healing_potion_1",
        name: "治疗药水 (Potion of Healing)",
        category: "potion",
        quantity: 2,
        unit_weight_lb: 0.5,
        price_cp: 5000,
        source_label: "official",
        location_key: "loc_redfall_keep_entrance",
        is_hidden: false,
        description: "装在带软木塞玻璃瓶中的闪亮红色液体，饮用恢复 2d4+2 点生命值。",
      },
      {
        key: "item_dusk_bell_dagger",
        name: "暮钟短剑 +1 (Dagger of the Dusk Bell)",
        category: "weapon",
        quantity: 1,
        unit_weight_lb: 1.0,
        price_cp: 25000,
        source_label: "custom",
        location_key: "loc_crypt_of_bellringer",
        is_hidden: true,
        description: "剑柄镶嵌小钟铃铛的魔法短剑。命中时造成 1d4+1 穿刺伤害，且受击目标在下回合开始前先攻判定获得劣势。",
      },
    ],
  },
};
