"""campaign state and audit

Revision ID: fb7d3fc91b8a
Revises: 20260725_0001
Create Date: 2026-07-25 19:22:24.913992
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fb7d3fc91b8a"
down_revision: str | None = "20260725_0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("world_setting", sa.String(length=200), nullable=True),
        sa.Column("current_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_location_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_campaign_name_nonempty"),
        sa.ForeignKeyConstraint(["current_location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.create_index("ix_campaigns_status_created", ["status", "created_at"], unique=False)

    op.create_table(
        "audit_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=True),
        sa.Column("actor", sa.String(length=80), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("before_json", sa.JSON(), nullable=True),
        sa.Column("after_json", sa.JSON(), nullable=True),
        sa.Column("request_id", sa.String(length=120), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.create_index(
            "ix_audit_campaign_created", ["campaign_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "characters",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("class_name", sa.String(length=100), nullable=True),
        sa.Column("level", sa.Integer(), server_default="1", nullable=False),
        sa.Column("hp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_hp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("inventory", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("hp >= 0 AND max_hp >= 0 AND hp <= max_hp", name="ck_character_hp"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_character_name_nonempty"),
        sa.CheckConstraint("level >= 1 AND level <= 20", name="ck_character_level"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.create_index(
            "ix_characters_campaign_created", ["campaign_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "combats",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=30), server_default="active", nullable=False),
        sa.Column("round_number", sa.Integer(), server_default="1", nullable=False),
        sa.Column("current_turn_index", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("current_turn_index >= 0", name="ck_combat_turn"),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_combat_name_nonempty"),
        sa.CheckConstraint("round_number >= 1", name="ck_combat_round"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("combats", schema=None) as batch_op:
        batch_op.create_index(
            "ix_combats_campaign_status", ["campaign_id", "status", "id"], unique=False
        )

    op.create_table(
        "locations",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_location_name_nonempty"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_locations_campaign_created", ["campaign_id", "created_at", "id"], unique=False
        )

    op.create_table(
        "quests",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="open", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_quest_name_nonempty"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_quests_campaign_status", ["campaign_id", "status", "id"], unique=False
        )

    op.create_table(
        "character_conditions",
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("condition_name", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("duration", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(condition_name)) > 0", name="ck_condition_name_nonempty"),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clues",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("quest_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("discovered", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_event_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_clue_name_nonempty"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["quest_id"], ["quests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("clues", schema=None) as batch_op:
        batch_op.create_index(
            "ix_clues_campaign_discovered", ["campaign_id", "discovered", "id"], unique=False
        )

    op.create_table(
        "combatants",
        sa.Column("combat_id", sa.String(length=36), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("initiative", sa.Integer(), server_default="0", nullable=False),
        sa.Column("hp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_hp", sa.Integer(), server_default="0", nullable=False),
        sa.Column("conditions", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("hp >= 0 AND max_hp >= 0 AND hp <= max_hp", name="ck_combatant_hp"),
        sa.CheckConstraint(
            "initiative >= -100 AND initiative <= 1000", name="ck_combatant_initiative"
        ),
        sa.CheckConstraint("length(trim(display_name)) > 0", name="ck_combatant_name_nonempty"),
        sa.ForeignKeyConstraint(["combat_id"], ["combats.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=80), server_default="note", nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("location_id", sa.String(length=36), nullable=True),
        sa.Column("visibility", sa.String(length=30), server_default="dm", nullable=False),
        sa.Column("metadata_json", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(title)) > 0", name="ck_event_title_nonempty"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "location_connections",
        sa.Column("from_location_id", sa.String(length=36), nullable=False),
        sa.Column("to_location_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=True),
        sa.Column("travel_time", sa.String(length=100), nullable=True),
        sa.Column("bidirectional", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("from_location_id <> to_location_id", name="ck_connection_distinct"),
        sa.ForeignKeyConstraint(["from_location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "npcs",
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("personality", sa.Text(), nullable=True),
        sa.Column("relationship", sa.Text(), nullable=True),
        sa.Column("secrets", sa.Text(), nullable=True),
        sa.Column("known_information", sa.Text(), nullable=True),
        sa.Column("location_id", sa.String(length=36), nullable=True),
        sa.Column("status", sa.String(length=50), server_default="active", nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.CheckConstraint("length(trim(name)) > 0", name="ck_npc_name_nonempty"),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("npcs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_npcs_campaign_created", ["campaign_id", "created_at", "id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("npcs", schema=None) as batch_op:
        batch_op.drop_index("ix_npcs_campaign_created")

    op.drop_table("npcs")
    op.drop_table("location_connections")
    op.drop_table("events")
    op.drop_table("combatants")
    with op.batch_alter_table("clues", schema=None) as batch_op:
        batch_op.drop_index("ix_clues_campaign_discovered")

    op.drop_table("clues")
    op.drop_table("character_conditions")
    with op.batch_alter_table("quests", schema=None) as batch_op:
        batch_op.drop_index("ix_quests_campaign_status")

    op.drop_table("quests")
    with op.batch_alter_table("locations", schema=None) as batch_op:
        batch_op.drop_index("ix_locations_campaign_created")

    op.drop_table("locations")
    with op.batch_alter_table("combats", schema=None) as batch_op:
        batch_op.drop_index("ix_combats_campaign_status")

    op.drop_table("combats")
    with op.batch_alter_table("characters", schema=None) as batch_op:
        batch_op.drop_index("ix_characters_campaign_created")

    op.drop_table("characters")
    with op.batch_alter_table("audit_log", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_campaign_created")

    op.drop_table("audit_log")
    with op.batch_alter_table("campaigns", schema=None) as batch_op:
        batch_op.drop_index("ix_campaigns_status_created")

    op.drop_table("campaigns")
    # ### end Alembic commands ###
